apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: web # Выбираем Pods с этим лейблом
  ports:
    - protocol  : TCP
      port      : 80 # Port on Service
      targetPort: 8000 # Port on Pod
  type: LoadBalancer